services:
  docs:
    image: example_django_cookiecutter_local_docs
    container_name: example_django_cookiecutter_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./example_django_cookiecutter:/app/example_django_cookiecutter:z
    ports:
      - '9000:9000'
    command: /start-docs
